# CONSTANTES FOR BASE MENU
MENU_CLIENTS = 1
MENU_CONTRATS = 2
MENU_EVENEMENTS = 3
MENU_EXIT = 4

# CONSTANCES FOR CUSTOMER MENU
MENU_CUSTOMER_CREATION = 1
MENU_CUSTOMER_UPDATE = 2
MENU_CUSTOMER_DELETE = 3
MENU_CUSTOMER_EXIT = 4

DB_USER = 'root'
DB_PASSWORD = 'Toto1234!'
DB_HOST = 'localhost'
DB_NAME = 'epicevents'
DB_URL = f'mysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}'
