# CONSTANTS FOR CONTRACT MENU
MENU_CONTRACT_CREATION = 1
MENU_CONTRACT_UPDATE = 2
MENU_CONTRACT_DELETE = 3
MENU_CONTRACT_SIGNATURE = 4
MENU_CONTRACT_FILTER = 5
MENU_CONTRACT_EXIT = 6

MENU_CONTRACT_FILTER_BY_SIGNATURE = 1
MENU_CONTRACT_FILTER_NOT_FULLY_PAYED = 2
MENU_CONTRACT_FILTER_EXIT = 6