# CONSTANTS FOR EVENT MENU
MENU_EVENT_CREATION = 1
MENU_EVENT_ASSIGNATION = 2
MENU_EVENT_UPDATE = 3
MENU_EVENT_DELETE = 4
MENU_EVENT_FILTER = 5
MENU_EVENT_EXIT = 6

MENU_EVENT_FILTER_NOT_ASSIGNED = 1
MENU_EVENT_FILTER_IN_PROGRESS = 2
MENU_EVENT_FILTER_ASSIGNED = 3
MENU_EVENT_FILTER_EXIT = 6